### ISSUE TITLE
2. MVP - PAGE (Categories/Mobile) - Sort button needs to be added 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#125] opened 2021-09-14 15:16 UTC
<img width="152" alt="Screen Shot 2021-09-14 at 11 04 15 AM" src="https://user-images.githubusercontent.com/90408712/133284985-ed19a887-dcbc-4e7a-b085-e1b57e92cc2e.png">

**Comment by 1stevengrant** [comment] 2021-09-30 21:23
duplicate of #128

**Closed by 1stevengrant** 2021-09-30 21:23 UTC
Labels: duplicate
